"use client";

import Link from "next/link";
import { useCallback, useEffect, useEffectEvent, useMemo, useRef, useState } from "react";
import {
  createFrameFactoryAdapter,
  type Channel,
  type ComparisonResult,
  type FrameFactoryAdapter,
  type JsonObject,
  type JsonValue,
  type Run,
  type SkillDetail,
  type SkillSpec,
  type SkillVersion,
  type ValidationReport,
} from "@/lib/api";
import { Badge, LoadingScaffold, StatePanel } from "@/components/page-heading";
import { UiSelect } from "@/components/ui-select";

export type StudioView = "overview" | "editor" | "test" | "versions" | "usage" | "publish";
type EditorSection = "basic" | "input" | "research" | "writing" | "visual" | "voice" | "editing" | "qc" | "pipeline" | "output";
type EditorIssue = { message: string; line: number; column: number; path: string };
type Adapter = FrameFactoryAdapter;

const studioViews: Array<{ id: StudioView; label: string; suffix: string }> = [
  { id: "overview", label: "概览", suffix: "" },
  { id: "editor", label: "编辑器", suffix: "/edit" },
  { id: "test", label: "测试实验室", suffix: "/test" },
  { id: "versions", label: "版本", suffix: "/versions" },
  { id: "usage", label: "使用情况", suffix: "/usage" },
  { id: "publish", label: "发布检查", suffix: "/publish" },
];

const editorSections: Array<{ id: EditorSection; index: string; label: string; help: string }> = [
  { id: "basic", index: "01", label: "基本信息", help: "身份、可见性与当前编辑版本" },
  { id: "input", index: "02", label: "输入 Schema", help: "定义 Run 接收的结构化输入" },
  { id: "research", index: "03", label: "研究与事实策略", help: "设定事实边界、引用与来源偏好" },
  { id: "writing", index: "04", label: "写作策略", help: "控制表达方法与内容约束" },
  { id: "visual", index: "05", label: "视觉与素材策略", help: "约束画面方向、素材和外部获取" },
  { id: "voice", index: "06", label: "配音与字幕", help: "声明音频与字幕执行能力" },
  { id: "editing", index: "07", label: "剪辑策略", help: "设定镜头指引和剪辑能力" },
  { id: "qc", index: "08", label: "QC 门禁", help: "配置可计算的质量验收规则" },
  { id: "pipeline", index: "09", label: "Pipeline", help: "绑定默认 Pipeline 和模型能力" },
  { id: "output", index: "10", label: "输出契约", help: "定义下游可依赖的输出字段" },
];

const statusLabels = { draft: "草稿", validating: "校验中", ready: "可发布", published: "已发布", deprecated: "已停用" };

export function SkillStudio({ skillId, initialView }: { skillId: string; initialView: StudioView }) {
  const adapter = useMemo(() => createFrameFactoryAdapter(), []);
  const [detail, setDetail] = useState<SkillDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    const result = await adapter.getSkill(skillId);
    if (result.ok) setDetail(result.data); else setError(result.error.message);
    setLoading(false);
  }, [adapter, skillId]);
  useEffect(() => {
    let cancelled = false;
    adapter.getSkill(skillId).then((result) => {
      if (cancelled) return;
      if (result.ok) setDetail(result.data); else setError(result.error.message);
      setLoading(false);
    });
    return () => { cancelled = true; };
  }, [adapter, skillId]);

  if (loading) return <div className="page page--wide"><h1 className="sr-only" tabIndex={-1}>Skill 正在加载</h1><LoadingScaffold title="正在打开 Skill 工作台" description="正在同步规格、版本、测试记录与使用数据。" /></div>;
  if (!detail) return <div className="page"><h1 className="sr-only" tabIndex={-1}>Skill 不可用</h1><StatePanel code="ERR" title="无法打开这个 Skill" description={error || "它可能已移出当前工作区。"} error><button className="button-secondary" type="button" onClick={() => void load()}>重试</button><Link className="button-ghost" href="/skills">返回列表</Link></StatePanel></div>;

  const basePath = `/skills/${detail.skill.id}`;
  return (
    <div className="page page--wide">
      <header className="studio-header">
        <div className="studio-title"><p className="eyebrow">SKILL STUDIO / {detail.skill.publisher.type === "system" ? "OFFICIAL" : detail.skill.forkedFrom ? "FORK" : "MY SKILL"}</p><h1 tabIndex={-1}>{detail.skill.name}</h1><p>{detail.skill.description}</p></div>
        <div className="page-actions"><Badge tone={detail.skill.publisher.type === "system" ? "accent" : "neutral"}>{detail.skill.publisher.type === "system" ? "官方 Skill" : detail.skill.forkedFrom ? "分叉 Skill" : "我的 Skill"}</Badge><Badge tone={detail.skill.status === "published" ? "success" : "warning"}>{statusLabels[detail.skill.status]}</Badge>{!detail.skill.permissions.edit && detail.skill.permissions.fork ? <Link className="button-secondary" href={`/skills/new?method=fork&source=${encodeURIComponent(detail.skill.id)}`}>分叉为我的 Skill</Link> : null}<Link className="button-ghost" href="/skills">返回列表</Link></div>
      </header>
      <div className="studio-nav"><nav className="tabs" aria-label="Skill 页面">{studioViews.map((view) => <Link key={view.id} className="tab" aria-current={initialView === view.id ? "page" : undefined} href={`${basePath}${view.suffix}`}>{view.label}</Link>)}</nav><span className="muted">{detail.versions.length} 个版本 · {detail.skill.stats.runCount} 次使用</span></div>
      {initialView === "overview" ? <OverviewView detail={detail} /> : null}
      {initialView === "editor" ? <EditorView adapter={adapter} detail={detail} onUpdate={setDetail} /> : null}
      {initialView === "test" ? <TestBench adapter={adapter} detail={detail} onUpdate={setDetail} /> : null}
      {initialView === "versions" ? <VersionHistory adapter={adapter} detail={detail} onUpdate={setDetail} /> : null}
      {initialView === "usage" ? <UsageView adapter={adapter} detail={detail} /> : null}
      {initialView === "publish" ? <PublishChecks adapter={adapter} detail={detail} onUpdate={setDetail} /> : null}
    </div>
  );
}

function currentVersion(detail: SkillDetail) { return detail.versions.find((item) => item.id === detail.skill.currentVersionId) ?? detail.versions.find((item) => item.state === "published"); }
function isMutableVersion(version: SkillVersion) { return ["draft", "ready", "rejected"].includes(version.state); }
function draftVersion(detail: SkillDetail) { return detail.versions.find((item) => item.id === detail.skill.draftVersionId && isMutableVersion(item)) ?? detail.versions.find(isMutableVersion); }
function displayDate(value?: string) { if (!value) return "—"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(parsed); }
function asRecord(value: JsonValue | undefined): JsonObject { return value && typeof value === "object" && !Array.isArray(value) ? value as JsonObject : {}; }
function textValue(value: JsonValue | undefined) { return typeof value === "string" ? value : ""; }

function OverviewView({ detail }: { detail: SkillDetail }) {
  const published = currentVersion(detail); const draft = draftVersion(detail); const active = draft ?? published ?? detail.versions[0];
  if (!active) return <StatePanel code="00" title="还没有版本" description="该 Skill 尚未生成可查看的版本。" />;
  const complete = [active.spec.inputSchema, active.spec.researchPolicy, active.spec.writingInstructions, active.spec.visualPolicy, active.spec.assetPolicy, active.spec.qcRubric, active.spec.outputContract, active.spec.modelRequirements].filter(Boolean).length;
  return (
    <div className="overview-layout">
      <section className="overview-main" aria-labelledby="overview-title"><div className="section-heading"><div><p className="eyebrow">OVERVIEW</p><h2 id="overview-title">Skill 概览</h2></div><Badge tone={draft ? "warning" : "success"}>{draft ? `正在编辑 ${draft.version}` : `当前 ${active.version}`}</Badge></div><dl className="overview-metrics"><div><dt>当前发布版本</dt><dd>{published?.version ?? "尚未发布"}</dd></div><div><dt>规格完整度</dt><dd>{complete} / 8</dd></div><div><dt>历史版本</dt><dd>{detail.versions.length}</dd></div><div><dt>Run 引用</dt><dd>{detail.skill.stats.runCount}</dd></div></dl><div className="overview-section-grid"><article className="panel"><p className="eyebrow">INPUT</p><h3>{Object.keys(asRecord(active.spec.inputSchema.properties)).length} 个输入字段</h3><p>{textValue(active.spec.inputSchema.description) || "未填写输入说明"}</p></article><article className="panel"><p className="eyebrow">RESEARCH</p><h3>{active.spec.researchPolicy.requireCitations ? "要求引用来源" : "允许归因说明"}</h3><p>{active.spec.researchPolicy.preferredSources.length} 类优先来源</p></article><article className="panel"><p className="eyebrow">OUTPUT</p><h3>{active.spec.outputContract.format}</h3><p>{active.spec.outputContract.fields.length} 个声明字段</p></article><article className="panel"><p className="eyebrow">PIPELINE</p><h3>{active.spec.defaultPipelineVersionId ? "已绑定默认版本" : "由 Run 选择"}</h3><p>{active.spec.modelRequirements.capabilities.length} 项能力要求</p></article></div></section>
      <aside className="overview-side" aria-label="Skill 状态与下一步"><section className="panel"><p className="eyebrow">IDENTITY</p><dl className="detail-list"><div><dt>发布者</dt><dd>{detail.skill.publisher.displayName}</dd></div><div><dt>可见性</dt><dd>{detail.skill.visibility === "private" ? "私有" : detail.skill.visibility === "workspace" ? "工作区" : "公开只读"}</dd></div><div><dt>更新时间</dt><dd>{displayDate(detail.skill.updatedAt)}</dd></div><div><dt>来源</dt><dd>{detail.skill.forkedFrom ? "分叉副本" : detail.skill.publisher.type === "system" ? "官方维护" : "工作区创建"}</dd></div></dl></section><section className="panel"><p className="eyebrow">NEXT STEP</p><h2>{detail.skill.permissions.edit ? draft ? "继续完善草稿" : "开始下一版本" : "查看或分叉官方方法"}</h2><p className="muted">发布版本不可覆盖；后续修改必须进入新草稿。</p><div className="button-row">{detail.skill.permissions.edit ? <Link className="button" href={`/skills/${detail.skill.id}/edit`}>{draft ? "继续编辑" : "打开编辑器"}</Link> : <Link className="button" href={`/skills/new?method=fork&source=${encodeURIComponent(detail.skill.id)}`}>分叉 Skill</Link>}<Link className="button-secondary" href={`/skills/${detail.skill.id}/publish`}>发布检查</Link></div></section></aside>
    </div>
  );
}

function EditorView({ adapter, detail, onUpdate }: { adapter: Adapter; detail: SkillDetail; onUpdate: (value: SkillDetail) => void }) {
  const existingDraft = draftVersion(detail); const visible = existingDraft ?? currentVersion(detail) ?? detail.versions[0];
  const [section, setSection] = useState<EditorSection>("basic"); const [mode, setMode] = useState<"form" | "json">("form");
  const [working, setWorking] = useState<SkillSpec>(() => structuredClone(visible?.spec));
  const [jsonValue, setJsonValue] = useState(() => JSON.stringify(visible?.spec ?? {}, null, 2)); const [savedValue, setSavedValue] = useState(() => JSON.stringify(visible?.spec ?? {}, null, 2));
  const [issues, setIssues] = useState<EditorIssue[]>([]); const [status, setStatus] = useState(existingDraft && detail.skill.permissions.edit ? "草稿已同步" : "当前版本只读"); const [saving, setSaving] = useState(false); const editorRef = useRef<HTMLTextAreaElement>(null);
  const existingDraftId = existingDraft?.id; const existingDraftRevision = existingDraft?.revision;
  const editable = Boolean(existingDraft && isMutableVersion(existingDraft) && detail.skill.permissions.edit); const structuredValue = JSON.stringify(working, null, 2); const dirty = mode === "json" ? jsonValue !== savedValue : structuredValue !== savedValue;
  async function save() {
    if (!editable || !existingDraftId || existingDraftRevision === undefined || saving) return;
    let nextSpec = working;
    if (mode === "json") { const parsed = parseSpecJson(jsonValue); setIssues(parsed.issues); if (!parsed.spec) { setStatus("保存失败：请先修复 JSON 语法与 Schema 错误。"); return; } nextSpec = parsed.spec; }
    setSaving(true); setStatus("正在保存草稿…"); const result = await adapter.saveDraft(detail.skill.id, existingDraftId, { spec: nextSpec }, existingDraftRevision); setSaving(false);
    if (!result.ok) { setStatus(`保存失败：${result.error.message}。本地编辑仍保留。`); return; }
    const normalized = JSON.stringify(result.data.spec, null, 2); setWorking(structuredClone(result.data.spec)); setJsonValue(normalized); setSavedValue(normalized); setIssues([]); setStatus("草稿已保存"); onUpdate({ ...detail, skill: { ...detail.skill, status: "draft", draftVersionId: result.data.id }, versions: detail.versions.map((item) => item.id === result.data.id ? result.data : item) });
  }
  const saveFromShortcut = useEffectEvent(() => { void save(); });
  useEffect(() => { function shortcut(event: KeyboardEvent) { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "s") { event.preventDefault(); saveFromShortcut(); } } window.addEventListener("keydown", shortcut); return () => window.removeEventListener("keydown", shortcut); }, []);
  async function createDraft() { const source = currentVersion(detail) ?? detail.versions[0]; if (!source) return; setStatus("正在创建后续草稿…"); const result = await adapter.createDraft(detail.skill.id, source.id); if (!result.ok) return setStatus(`创建失败：${result.error.message}`); const normalized = JSON.stringify(result.data.spec, null, 2); setWorking(structuredClone(result.data.spec)); setJsonValue(normalized); setSavedValue(normalized); setStatus(`草稿 ${result.data.version} 已创建。`); onUpdate({ ...detail, skill: { ...detail.skill, status: "draft", draftVersionId: result.data.id }, versions: [result.data, ...detail.versions] }); }
  function switchMode(next: "form" | "json") { if (next === mode) return; if (next === "json") { setJsonValue(structuredValue); setIssues([]); setMode(next); return; } const parsed = parseSpecJson(jsonValue); setIssues(parsed.issues); if (!parsed.spec) { setStatus("无法切回结构化表单：请先修复 JSON 错误。"); return; } setWorking(parsed.spec); setMode(next); }
  function focusIssue(issue: EditorIssue) { const index = indexFromLineColumn(jsonValue, issue.line, issue.column); editorRef.current?.focus(); editorRef.current?.setSelectionRange(index, index + 1); }
  if (!visible) return <StatePanel code="00" title="没有可编辑版本" description="请先为该 Skill 创建一个版本。" />;

  return (
    <section aria-labelledby="skill-editor-title"><div className="editor-toolbar"><div><p className="eyebrow">DECLARATIVE SPEC</p><h2 id="skill-editor-title">{editable ? `编辑草稿 ${visible.version}` : `查看版本 ${visible.version}`}</h2></div><div className="button-row" role="group" aria-label="编辑模式"><button className="button-ghost button-small" type="button" aria-pressed={mode === "form"} onClick={() => switchMode("form")}>结构化表单</button><button className="button-ghost button-small" type="button" aria-pressed={mode === "json"} onClick={() => switchMode("json")}>JSON 高级模式</button>{!editable && detail.skill.permissions.edit ? <button className="button" type="button" onClick={() => void createDraft()}>创建新草稿</button> : null}{!detail.skill.permissions.edit && detail.skill.permissions.fork ? <Link className="button" href={`/skills/new?method=fork&source=${encodeURIComponent(detail.skill.id)}`}>分叉后编辑</Link> : null}</div></div>
      {!editable ? <div className="alert" role="note"><strong>只读保护</strong>：{detail.skill.publisher.type === "system" ? "官方 Skill 不可直接修改，可分叉为自己的草稿。" : "已发布版本不可覆盖，请先创建后续草稿。"}</div> : null}
      {mode === "form" ? <div className="studio-grid"><nav className="section-nav" aria-label="Skill 结构章节"><p className="eyebrow">SPEC SECTIONS</p>{editorSections.map((item) => <button key={item.id} type="button" aria-current={section === item.id} onClick={() => setSection(item.id)}>{item.label}<span>{item.index}</span></button>)}</nav><section className="editor-canvas" aria-labelledby="editor-section-title"><div className="editor-canvas-head"><div><h2 id="editor-section-title">{editorSections.find((item) => item.id === section)?.label}</h2><p>{editorSections.find((item) => item.id === section)?.help}</p></div><Badge tone={dirty ? "warning" : "success"}>{dirty ? "未保存" : "已同步"}</Badge></div><StructuredSection section={section} detail={detail} version={visible} value={working} disabled={!editable} onChange={setWorking} /></section><aside className="inspector" aria-label="版本检查器"><p className="eyebrow">INSPECTOR</p><h2>{visible.version} · revision {visible.revision}</h2><ul className="check-list"><li>输入 Schema 已定义</li><li>输出字段可机器校验</li><li className={visible.testTopics.length < 1 ? "is-pending" : ""}>测试主题 {visible.testTopics.length} / 1</li><li className={existingDraft?.state !== "ready" ? "is-pending" : ""}>{existingDraft?.state === "ready" ? "服务端校验已通过" : existingDraft?.state === "rejected" ? "校验未通过，可继续编辑" : existingDraft ? "等待服务端发布校验" : "发布内容受不可变保护"}</li></ul><p className="inspector-note">配音、字幕和剪辑在当前契约中以能力要求持久化；API 没有独立策略对象。</p></aside></div> : <div className="advanced-editor panel"><div className="field"><label htmlFor="skill-json-editor">完整 Skill 规格 JSON</label><textarea ref={editorRef} id="skill-json-editor" className="textarea code-area" value={jsonValue} readOnly={!editable} spellCheck={false} aria-invalid={issues.length > 0} aria-describedby="json-editor-help json-error-list" onChange={(event) => { const next = event.target.value; setJsonValue(next); setIssues(parseSpecJson(next).issues); }} /><span id="json-editor-help" className="field-help">仅接受声明式规格，不接受代码、路径或未知执行字段。</span></div><div id="json-error-list" className="json-errors" aria-live="polite">{issues.length ? <><strong>发现 {issues.length} 个问题</strong><ol>{issues.map((issue, index) => <li key={`${issue.path}-${index}`}><button type="button" onClick={() => focusIssue(issue)}>第 {issue.line} 行，第 {issue.column} 列：{issue.message}</button></li>)}</ol></> : <p>语法与本地 Schema 检查通过；发布前仍需服务端校验。</p>}</div></div>}
      <div className="editor-savebar theme-inverse"><p className="status-line" role="status" aria-live="polite">{status}</p><div className="button-row"><button className="button" type="button" onClick={() => void save()} disabled={!editable || !dirty || saving}>{saving ? "正在保存…" : "保存草稿"}</button><Link className="button-secondary" href={`/skills/${detail.skill.id}/publish`}>前往发布检查</Link></div></div>
    </section>
  );
}

function StructuredSection({ section, detail, version, value, disabled, onChange }: { section: EditorSection; detail: SkillDetail; version: SkillVersion; value: SkillSpec; disabled: boolean; onChange: (value: SkillSpec) => void }) {
  const update = <K extends keyof SkillSpec>(key: K, next: SkillSpec[K]) => onChange({ ...value, [key]: next });
  const capabilities = value.modelRequirements.capabilities;
  const toggleCapability = (name: string, enabled: boolean) => update("modelRequirements", { ...value.modelRequirements, capabilities: enabled ? Array.from(new Set([...capabilities, name])) : capabilities.filter((item) => item !== name) });
  if (section === "basic") return <div className="editor-fields"><div className="form-grid"><div className="field"><label htmlFor="skill-basic-name">名称</label><input id="skill-basic-name" className="input" value={detail.skill.name} readOnly /></div><div className="field"><label htmlFor="skill-basic-version">版本</label><input id="skill-basic-version" className="input" value={version.version} readOnly /></div><div className="field field--full"><label htmlFor="skill-basic-description">说明</label><textarea id="skill-basic-description" className="textarea" value={detail.skill.description} readOnly /></div></div><div className="alert" role="note">Skill 身份由独立端点维护；当前版本编辑器只处理声明式规格，因此名称、说明和可见性在此只读。</div></div>;
  if (section === "input") return <InputSchemaFields value={value} disabled={disabled} onChange={(inputSchema) => update("inputSchema", inputSchema)} />;
  if (section === "research") return <div className="editor-fields"><div className="form-grid"><div className="field"><span className="field-label">事实边界</span><UiSelect ariaLabel="事实边界" value={value.researchPolicy.factBoundary === "strict" ? "strict" : "balanced"} disabled={disabled} onChange={(factBoundary) => update("researchPolicy", { ...value.researchPolicy, factBoundary: factBoundary as "strict" | "balanced" })}><option value="strict">严格：排除未验证事实</option><option value="balanced">平衡：引用或归因</option></UiSelect></div><label className="checkbox-field" aria-label="要求引用"><input type="checkbox" checked={value.researchPolicy.requireCitations} disabled={disabled || value.researchPolicy.factBoundary === "strict"} onChange={(event) => update("researchPolicy", { ...value.researchPolicy, requireCitations: event.target.checked })} /><span><strong>要求引用</strong><small>严格模式固定排除未验证事实；平衡模式可在引用与归因间选择</small></span></label><ListField id="preferred-sources" label="允许的来源类型（每行一项）" value={value.researchPolicy.preferredSources} disabled={disabled} onChange={(preferredSources) => update("researchPolicy", { ...value.researchPolicy, preferredSources })} /><ListField id="excluded-sources" label="阻止的域名（每行一项）" value={value.researchPolicy.excludedSources} disabled={disabled} onChange={(excludedSources) => update("researchPolicy", { ...value.researchPolicy, excludedSources })} /></div><div className="alert" role="note">Canonical 契约不支持“创意事实边界”，因此这里不会提供一个无法持久化的伪选项。</div></div>;
  if (section === "writing") return <div className="editor-fields"><div className="field"><label htmlFor="writing-instructions">方法与写作指令</label><textarea id="writing-instructions" className="textarea policy-textarea" value={value.writingInstructions} readOnly={disabled} onChange={(event) => update("writingInstructions", event.target.value)} /><span className="field-help">这是惰性 Markdown 指令，不会作为代码执行。</span></div></div>;
  if (section === "visual") return <div className="editor-fields"><div className="form-grid"><div className="field field--full"><label htmlFor="visual-direction">主视觉标签</label><input id="visual-direction" className="input" value={value.visualPolicy.direction} readOnly={disabled} onChange={(event) => update("visualPolicy", { ...value.visualPolicy, direction: event.target.value })} /></div><ListField id="asset-tags" label="允许的素材类型（每行一项）" value={value.assetPolicy.requiredTags} disabled={disabled} onChange={(requiredTags) => update("assetPolicy", { ...value.assetPolicy, requiredTags })} /><div className="field"><span className="field-label">素材库绑定</span><UiSelect ariaLabel="素材策略" value={value.assetPolicy.strategy} disabled={disabled} onChange={(strategy) => update("assetPolicy", { ...value.assetPolicy, strategy: strategy as typeof value.assetPolicy.strategy })}><option value="channel_default">跟随频道</option><option value="workspace_libraries">由 Run 选择素材库</option><option value="explicit_only">不绑定素材库</option></UiSelect></div><label className="checkbox-field" aria-label="允许授权图库回退"><input type="checkbox" checked={value.assetPolicy.allowExternalAcquisition} disabled={disabled} onChange={(event) => update("assetPolicy", { ...value.assetPolicy, allowExternalAcquisition: event.target.checked })} /><span><strong>允许授权图库回退</strong><small>关闭时素材不足会失败；已有 generated 回退会原样保留，除非你修改此项</small></span></label></div><div className="alert" role="note">当前 Canonical 契约没有“禁止画面处理”字段，未展示该控件，避免产生无法保存的配置。</div></div>;
  if (section === "voice") return <CapabilityFields disabled={disabled} items={[{ id: "voice.synthesis", label: "需要配音合成", copy: "Run 必须提供兼容配音能力" }, { id: "render.subtitles", label: "需要字幕渲染", copy: "Run 必须提供字幕能力" }]} selected={capabilities} onToggle={toggleCapability} note="当前 SkillVersion API 只支持能力声明，不支持保存音色、语速或字幕样式；具体值由 Run / 频道组合提供。" />;
  if (section === "editing") return <div className="editor-fields"><ListField id="shot-guidance" label="镜头与剪辑指引（每行一项）" value={value.visualPolicy.shotGuidance} disabled={disabled} onChange={(shotGuidance) => update("visualPolicy", { ...value.visualPolicy, shotGuidance })} /><CapabilityFields disabled={disabled} items={[{ id: "editing.timeline", label: "需要时间线剪辑", copy: "Pipeline 必须支持镜头编排" }, { id: "editing.transitions", label: "需要转场能力", copy: "Pipeline 必须支持受控转场" }]} selected={capabilities} onToggle={toggleCapability} note="当前 API 没有独立 editing_policy；这里保存镜头指引和能力要求，不伪造额外策略字段。" /></div>;
  if (section === "qc") return <QcFields value={value} disabled={disabled} onChange={(qcRubric) => update("qcRubric", qcRubric)} />;
  if (section === "pipeline") return <div className="editor-fields"><div className="field"><label htmlFor="pipeline-version">默认 Pipeline Version ID</label><input id="pipeline-version" className="input code-input" value={value.defaultPipelineVersionId ?? ""} readOnly={disabled} onChange={(event) => update("defaultPipelineVersionId", event.target.value || undefined)} placeholder="留空则由 Run 或频道选择" /></div><ListField id="model-capabilities" label="全部能力要求（每行一项）" value={capabilities} disabled={disabled} onChange={(next) => update("modelRequirements", { ...value.modelRequirements, capabilities: next })} /><div className="alert" role="note">Canonical SkillVersion 只声明能力与最低版本，不支持 preferredModel；模型选择由部署或 Run 负责。</div></div>;
  return <div className="editor-fields"><div className="form-grid"><div className="field"><span className="field-label">首个产物类型</span><UiSelect ariaLabel="首个产物类型" value={value.outputContract.format} disabled={disabled} onChange={(format) => update("outputContract", { ...value.outputContract, format })}><option value="research">研究</option><option value="script">脚本</option><option value="image">图片</option><option value="video">视频</option><option value="audio">音频</option><option value="subtitle">字幕</option><option value="manifest">清单</option><option value="qc_report">质检报告</option><option value="log_archive">日志归档</option></UiSelect></div><ListField id="output-fields" label="产物名称（每行一项）" value={value.outputContract.fields} disabled={disabled} onChange={(fields) => update("outputContract", { ...value.outputContract, fields })} /></div><div className="alert" role="note">语言与目标时长属于 Canonical writing_policy，目前在结构化表单中只读并原样保留；不会用 output_contract 中的伪字段假保存。</div></div>;
}

function InputSchemaFields({ value, disabled, onChange }: { value: SkillSpec; disabled: boolean; onChange: (value: JsonObject) => void }) {
  const schema = value.inputSchema; const properties = asRecord(schema.properties); const required = Array.isArray(schema.required) ? schema.required.filter((item): item is string => typeof item === "string") : [];
  function changeProperty(oldName: string, name: string, patch: JsonObject) { const next = { ...properties }; const current = asRecord(next[oldName]); delete next[oldName]; next[name || oldName] = { ...current, ...patch }; onChange({ ...schema, properties: next, required: required.map((item) => item === oldName ? (name || oldName) : item) }); }
  return <div className="editor-fields"><div className="form-grid"><div className="field"><label htmlFor="schema-title">Schema 名称</label><input id="schema-title" className="input" value={textValue(schema.title)} readOnly={disabled} onChange={(event) => onChange({ ...schema, title: event.target.value })} /></div><div className="field"><label htmlFor="schema-description">输入说明</label><input id="schema-description" className="input" value={textValue(schema.description)} readOnly={disabled} onChange={(event) => onChange({ ...schema, description: event.target.value })} /></div></div><div className="field-array"><div className="field-array-heading"><strong>输入字段</strong><button className="button-ghost button-small" type="button" disabled={disabled} onClick={() => { let index = Object.keys(properties).length + 1; while (properties[`field_${index}`]) index += 1; onChange({ ...schema, properties: { ...properties, [`field_${index}`]: { type: "string", title: `字段 ${index}` } } }); }}>添加字段</button></div>{Object.entries(properties).map(([name, raw]) => { const field = asRecord(raw); return <div className="field-array-row input-field-row" key={name}><div className="field"><label htmlFor={`input-name-${name}`}>字段名</label><input id={`input-name-${name}`} className="input code-input" value={name} readOnly={disabled} onChange={(event) => changeProperty(name, event.target.value.replace(/[^a-z0-9_]/g, ""), {})} /></div><div className="field"><label htmlFor={`input-title-${name}`}>显示名称</label><input id={`input-title-${name}`} className="input" value={textValue(field.title) || name} readOnly={disabled} onChange={(event) => changeProperty(name, name, { title: event.target.value })} /></div><div className="field"><span className="field-label">类型</span><UiSelect ariaLabel={`${name} 类型`} value={textValue(field.type) || "string"} disabled={disabled} onChange={(type) => changeProperty(name, name, { type })}><option value="string">文本</option><option value="integer">整数</option><option value="number">数字</option><option value="boolean">布尔值</option><option value="array">数组</option></UiSelect></div><label className="compact-check"><input type="checkbox" checked={required.includes(name)} disabled={disabled} onChange={(event) => onChange({ ...schema, required: event.target.checked ? [...required, name] : required.filter((item) => item !== name) })} />必填</label><button className="button-ghost button-small" type="button" disabled={disabled} onClick={() => { const next = { ...properties }; delete next[name]; onChange({ ...schema, properties: next, required: required.filter((item) => item !== name) }); }}>删除</button></div>; })}</div></div>;
}

function QcFields({ value, disabled, onChange }: { value: SkillSpec; disabled: boolean; onChange: (value: SkillSpec["qcRubric"]) => void }) {
  const criteria = value.qcRubric.criteria;
  return <div className="editor-fields"><div className="field-array"><div className="field-array-heading"><strong>质量规则</strong><button className="button-ghost button-small" type="button" disabled={disabled} onClick={() => onChange({ criteria: [...criteria, { id: `rule-${criteria.length + 1}`, label: `rule-${criteria.length + 1}`, description: "", minimumScore: 1 }] })}>添加规则</button></div>{criteria.map((item, index) => <div className="field-array-row qc-field-row" key={`${item.id}-${index}`}><div className="field"><label htmlFor={`qc-id-${index}`}>规则 ID</label><input id={`qc-id-${index}`} className="input code-input" value={item.id} readOnly={disabled} onChange={(event) => { const id = event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""); onChange({ criteria: criteria.map((current, currentIndex) => currentIndex === index ? { ...current, id, label: id } : current) }); }} /></div><div className="field"><label htmlFor={`qc-description-${index}`}>通过条件</label><input id={`qc-description-${index}`} className="input" value={item.description} readOnly={disabled} onChange={(event) => onChange({ criteria: criteria.map((current, currentIndex) => currentIndex === index ? { ...current, description: event.target.value } : current) })} /></div><button className="button-ghost button-small" type="button" disabled={disabled} onClick={() => onChange({ criteria: criteria.filter((_, currentIndex) => currentIndex !== index) })}>删除</button></div>)}</div><div className="alert" role="note">规则 category、severity、action 与全局最低通过率由 Canonical 契约保存并原样保留；此表单只修改规则 ID 和通过条件。</div></div>;
}

function ListField({ id, label, value, disabled, onChange }: { id: string; label: string; value: string[]; disabled: boolean; onChange: (value: string[]) => void }) { return <div className="field"><label htmlFor={id}>{label}</label><textarea id={id} className="textarea list-textarea" value={value.join("\n")} readOnly={disabled} onChange={(event) => onChange(event.target.value.split("\n").map((item) => item.trim()).filter(Boolean))} /></div>; }
function CapabilityFields({ items, selected, disabled, onToggle, note }: { items: Array<{ id: string; label: string; copy: string }>; selected: string[]; disabled: boolean; onToggle: (id: string, selected: boolean) => void; note: string }) { return <div className="editor-fields"><div className="capability-check-grid">{items.map((item) => <label className="checkbox-field" aria-label={item.label} key={item.id}><input type="checkbox" checked={selected.includes(item.id)} disabled={disabled} onChange={(event) => onToggle(item.id, event.target.checked)} /><span><strong>{item.label}</strong><small>{item.copy}</small></span></label>)}</div><div className="alert" role="note">{note}</div></div>; }

function parseSpecJson(source: string): { spec?: SkillSpec; issues: EditorIssue[] } {
  let parsed: unknown;
  try { parsed = JSON.parse(source); } catch (error) { const message = error instanceof Error ? error.message : "JSON 语法错误"; const match = message.match(/position\s+(\d+)/i); const location = lineColumnFromIndex(source, match ? Number(match[1]) : 0); return { issues: [{ message, ...location, path: "$" }] }; }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return { issues: [{ message: "根节点必须是对象", line: 1, column: 1, path: "$" }] };
  const record = parsed as Record<string, unknown>; const issues: EditorIssue[] = []; const required: Array<[keyof SkillSpec, "object" | "string"]> = [["inputSchema", "object"], ["researchPolicy", "object"], ["writingInstructions", "string"], ["visualPolicy", "object"], ["assetPolicy", "object"], ["qcRubric", "object"], ["outputContract", "object"], ["modelRequirements", "object"]];
  const allowedKeys = new Set(["inputSchema", "researchPolicy", "writingInstructions", "visualPolicy", "assetPolicy", "qcRubric", "outputContract", "modelRequirements", "defaultPipelineVersionId"]);
  for (const key of Object.keys(record)) if (!allowedKeys.has(key)) issues.push(issueAtKey(source, key, `Schema 不允许字段 ${key}`));
  for (const [key, kind] of required) { const item = record[key]; if (item === undefined) issues.push(issueAtKey(source, key, `缺少必填字段 ${key}`)); else if (kind === "object" ? (!item || typeof item !== "object" || Array.isArray(item)) : typeof item !== kind) issues.push(issueAtKey(source, key, `${key} 必须是${kind === "object" ? "对象" : "字符串"}`)); }
  const input = asRecord(record.inputSchema as JsonValue); if (input.type !== "object") issues.push(issueAtKey(source, "type", "inputSchema.type 必须为 object")); if (!input.properties || typeof input.properties !== "object" || Array.isArray(input.properties)) issues.push(issueAtKey(source, "properties", "inputSchema.properties 必须是对象")); if (!Array.isArray(input.required)) issues.push(issueAtKey(source, "required", "inputSchema.required 必须是数组"));
  const research = asRecord(record.researchPolicy as JsonValue); if (!["strict", "balanced", "creative"].includes(textValue(research.factBoundary))) issues.push(issueAtKey(source, "factBoundary", "factBoundary 必须是 strict、balanced 或 creative")); if (typeof research.requireCitations !== "boolean") issues.push(issueAtKey(source, "requireCitations", "requireCitations 必须是布尔值"));
  const qc = asRecord(record.qcRubric as JsonValue); if (!Array.isArray(qc.criteria) || qc.criteria.length === 0) issues.push(issueAtKey(source, "criteria", "QC 至少需要一条规则")); const output = asRecord(record.outputContract as JsonValue); if (!textValue(output.format)) issues.push(issueAtKey(source, "format", "输出格式不能为空")); if (!Array.isArray(output.fields) || output.fields.length === 0) issues.push(issueAtKey(source, "fields", "输出契约至少需要一个字段"));
  return issues.length ? { issues } : { spec: parsed as SkillSpec, issues: [] };
}
function issueAtKey(source: string, key: string, message: string): EditorIssue { const index = source.indexOf(`"${key}"`); return { message, ...lineColumnFromIndex(source, Math.max(index, 0)), path: key }; }
function lineColumnFromIndex(source: string, index: number) { const lines = source.slice(0, index).split("\n"); return { line: lines.length, column: (lines.at(-1)?.length ?? 0) + 1 }; }
function indexFromLineColumn(source: string, line: number, column: number) { return source.split("\n").slice(0, Math.max(line - 1, 0)).reduce((sum, item) => sum + item.length + 1, 0) + Math.max(column - 1, 0); }

function TestBench({ adapter, detail, onUpdate }: { adapter: Adapter; detail: SkillDetail; onUpdate: (value: SkillDetail) => void }) {
  const [topic, setTopic] = useState(""); const [inputs, setInputs] = useState("{}"); const [leftId, setLeftId] = useState(detail.versions[0]?.id ?? ""); const [rightId, setRightId] = useState(detail.versions[1]?.id ?? detail.versions[0]?.id ?? "");
  const [result, setResult] = useState<ComparisonResult | null>(null); const [running, setRunning] = useState(false); const [failure, setFailure] = useState<{ code: string; message: string } | null>(null); const [status, setStatus] = useState("填写输入并选择两个版本后运行真实测试。");
  async function runComparison() {
    if (!topic.trim() || !leftId || !rightId) return setStatus("请先填写主题并选择两个版本。");
    let parsedInputs: JsonObject;
    try { const parsed = JSON.parse(inputs) as unknown; if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("测试输入必须是 JSON 对象"); parsedInputs = parsed as JsonObject; } catch (error) { setFailure({ code: "INVALID_INPUT", message: error instanceof Error ? error.message : "测试输入 JSON 无效" }); return; }
    setRunning(true); setFailure(null); setResult(null); setStatus("正在用完全相同的输入执行两个版本…"); const response = await adapter.compareVersions({ skillId: detail.skill.id, leftVersionId: leftId, rightVersionId: rightId, topic: topic.trim(), inputs: parsedInputs }); setRunning(false);
    if (!response.ok) { setFailure({ code: response.error.code, message: response.error.message }); setStatus("测试失败；输入和版本选择已保留，可修正后重试。"); return; }
    setResult(response.data);
    const testedIds = new Set([leftId, rightId]);
    const drafts = detail.versions.filter((version) => isMutableVersion(version) && testedIds.has(version.id) && !version.testTopics.includes(topic.trim()));
    const savedTopics = await Promise.all(drafts.map((version) => adapter.saveDraft(detail.skill.id, version.id, { testTopics: [...version.testTopics, topic.trim()] }, version.revision)));
    const updatedVersions = detail.versions.map((version) => {
      const saved = savedTopics.find((item) => item.ok && item.data.id === version.id);
      return saved?.ok ? saved.data : version;
    });
    if (savedTopics.some((item) => !item.ok)) setStatus("真实测试已完成，但测试主题保存遇到版本冲突；结果仍可查看，请刷新后重试保存。");
    else { setStatus("真实测试已完成；输出、差异、耗时、成本和检查结果均来自服务端，测试主题已保存到草稿。"); onUpdate({ ...detail, versions: updatedVersions }); }
  }
  if (!detail.versions.length) return <StatePanel code="00" title="没有可测试版本" description="该 Skill 尚未生成任何版本，测试 API 暂时无法运行。" />;
  return <section aria-labelledby="test-bench-title"><div className="section-heading"><div><p className="eyebrow">CONTROLLED COMPARISON</p><h2 id="test-bench-title">测试实验室</h2></div><Badge>{detail.versions.length} 个可选版本</Badge></div><div className="test-controls test-controls--rich"><div className="field"><label htmlFor="test-topic">主题输入</label><input id="test-topic" className="input" value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="输入一次真实测试主题" /></div><div className="field"><label htmlFor="test-inputs">附加输入 JSON</label><textarea id="test-inputs" className="textarea code-area compact-code" value={inputs} spellCheck={false} onChange={(event) => setInputs(event.target.value)} /></div><div className="test-version-controls"><div className="field"><span className="field-label">版本 A</span><UiSelect ariaLabel="版本 A" value={leftId} onChange={setLeftId}>{detail.versions.map((version) => <option key={version.id} value={version.id}>{version.version} · {version.state}</option>)}</UiSelect></div><div className="field"><span className="field-label">版本 B</span><UiSelect ariaLabel="版本 B" value={rightId} onChange={setRightId}>{detail.versions.map((version) => <option key={version.id} value={version.id}>{version.version} · {version.state}</option>)}</UiSelect></div><button className="button" type="button" onClick={() => void runComparison()} disabled={running}>{running ? "运行中…" : "运行版本对比"}</button></div></div><p className="status-line" role="status" aria-live="polite" aria-busy={running}>{status}</p>{failure ? <StatePanel code={failure.code} title="测试失败" description={failure.message} error><button className="button-secondary" type="button" onClick={() => void runComparison()}>重试</button></StatePanel> : null}{!failure && result ? <><div className="comparison-grid"><ComparisonCard label="版本 A" side={result.left} /><ComparisonCard label="版本 B" side={result.right} /></div><section className="panel diff-panel" aria-labelledby="version-diff-title"><h3 id="version-diff-title">版本差异</h3>{result.differences.length ? <ul>{result.differences.map((difference, index) => <li key={`${difference.path}-${index}`}><Badge tone={difference.change === "added" ? "success" : difference.change === "removed" ? "warning" : "neutral"}>{difference.change}</Badge><code>{difference.path}</code><span>{difference.left ?? "—"} → {difference.right ?? "—"}</span></li>)}</ul> : <p className="muted">服务端未返回可展示的结构化差异。</p>}</section></> : null}{!failure && !result ? <StatePanel code="A/B" title="等待第一次真实测试" description="页面不会生成示例输出；只有测试 API 成功返回后才展示结果。" /> : null}</section>;
}

function ComparisonCard({ label, side }: { label: string; side: ComparisonResult["left"] }) { return <article className="panel comparison-card"><header><strong>{label} · {side.version}</strong><Badge tone={side.checks.every((item) => item.passed) ? "success" : "warning"}>{side.checks.filter((item) => item.passed).length} / {side.checks.length} 检查通过</Badge></header><dl className="metrics"><div><dt>成本</dt><dd>{side.cost.currency} {side.cost.amount.toFixed(2)}</dd></div><div><dt>耗时</dt><dd>{(side.durationMs / 1000).toFixed(1)} 秒</dd></div><div><dt>质量分</dt><dd>{Math.round((side.checks.reduce((sum, item) => sum + item.score, 0) / Math.max(side.checks.length, 1)) * 100)}</dd></div></dl><div className="output-copy"><h3>输出</h3><p>{side.output || "服务端返回了空输出。"}</p></div><ul className="check-list">{side.checks.map((check) => <li className={check.passed ? "" : "is-pending"} key={check.id}>{check.label}：{check.note}</li>)}</ul></article>; }

function VersionHistory({ adapter, detail, onUpdate }: { adapter: Adapter; detail: SkillDetail; onUpdate: (value: SkillDetail) => void }) {
  const [status, setStatus] = useState("发布版本不可覆盖或删除；当前控制 API 尚未提供回滚命令。");
  async function createDraft() { const source = currentVersion(detail) ?? detail.versions[0]; if (!source) return; setStatus("正在从当前版本创建草稿…"); const result = await adapter.createDraft(detail.skill.id, source.id); if (!result.ok) return setStatus(`创建草稿失败：${result.error.message}`); onUpdate({ ...detail, skill: { ...detail.skill, status: "draft", draftVersionId: result.data.id }, versions: [result.data, ...detail.versions] }); setStatus(`草稿 ${result.data.version} 已创建。`); }
  async function deleteDraft() { const draft = draftVersion(detail); if (!draft) return; setStatus("正在删除未发布草稿…"); const result = await adapter.deleteDraft(detail.skill.id); if (!result.ok) return setStatus(`删除失败：${result.error.message}`); if (!detail.skill.currentVersionId) { window.location.assign("/skills"); return; } onUpdate({ ...detail, skill: { ...detail.skill, status: "published", draftVersionId: undefined }, versions: detail.versions.filter((item) => item.id !== draft.id) }); setStatus("草稿已删除；发布版本和历史 Run 不受影响。"); }
  return <section aria-labelledby="version-history-title"><div className="section-heading"><div><p className="eyebrow">IMMUTABLE HISTORY</p><h2 id="version-history-title">版本历史</h2></div>{detail.skill.permissions.edit ? (draftVersion(detail) ? <Link className="button" href={`/skills/${detail.skill.id}/edit`}>继续编辑草稿</Link> : <button className="button" type="button" onClick={() => void createDraft()}>创建后续草稿</button>) : <Link className="button" href={`/skills/new?method=fork&source=${encodeURIComponent(detail.skill.id)}`}>分叉为我的 Skill</Link>}</div><p className="status-line" role="status" aria-live="polite">{status}</p>{detail.versions.length ? <div className="version-list">{detail.versions.map((version) => { const current = detail.skill.currentVersionId === version.id; return <article className="version-row" key={version.id}><div className="version-name"><strong>{version.version}</strong>{current ? <Badge tone="success">当前发布</Badge> : <Badge>{version.state}</Badge>}</div><div className="version-notes"><strong>{version.releaseNotes || "未填写发布说明"}</strong><p>content hash {version.contentHash?.slice(0, 12) || "仅草稿可变"}</p></div><p className="version-meta">创建人 {version.createdBy}<br />{version.testTopics.length} 个测试主题</p><p className="version-meta">revision {version.revision}<br />{displayDate(version.publishedAt ?? version.createdAt)}</p><div className="button-row">{version.state === "draft" && detail.skill.permissions.deleteDraft ? <button className="button-ghost button-small" type="button" onClick={() => void deleteDraft()}>删除草稿</button> : <button className="button-ghost button-small" type="button" disabled title={isMutableVersion(version) ? "校验后的待发布版本仍可继续编辑" : "发布版本受不可变保护"}>{isMutableVersion(version) ? "可继续编辑" : "受保护"}</button>}</div></article>; })}</div> : <StatePanel code="00" title="没有版本记录" description="该 Skill 尚未生成版本。" />}</section>;
}

function UsageView({ adapter, detail }: { adapter: Adapter; detail: SkillDetail }) {
  const [channels, setChannels] = useState<Channel[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [loading, setLoading] = useState(true); const [channelError, setChannelError] = useState(""); const [runError, setRunError] = useState("");
  const versionIds = useMemo(() => new Set(detail.versions.map((version) => version.id)), [detail.versions]);
  useEffect(() => {
    let cancelled = false;
    async function loadUsage() {
      const session = await adapter.getSession();
      if (!session.ok) { if (!cancelled) { const message = `无法确定当前工作区：${session.error.message}`; setChannelError(message); setRunError(message); setLoading(false); } return; }
      const [channelResult, runResult] = await Promise.all([adapter.listChannels({ workspaceId: session.data.activeWorkspaceId }), adapter.listRuns({ workspaceId: session.data.activeWorkspaceId })]); if (cancelled) return;
      if (channelResult.ok) setChannels(channelResult.data.filter((channel) => versionIds.has(channel.defaultComposition.skillVersionId))); else setChannelError(channelResult.error.message);
      if (runResult.ok) setRuns(runResult.data.filter((run) => versionIds.has(run.composition.skillVersionId))); else setRunError(runResult.error.message);
      setLoading(false);
    }
    void loadUsage(); return () => { cancelled = true; };
  }, [adapter, versionIds]);
  if (loading) return <div className="loading-grid" aria-label="正在读取真实使用数据"><div className="loading-card" /><div className="loading-card" /></div>;
  return <section aria-labelledby="usage-title"><div className="section-heading"><div><p className="eyebrow">REAL REFERENCES</p><h2 id="usage-title">使用情况</h2></div><span className="muted">只展示频道与 Run API 返回的数据</span></div><div className="usage-grid"><section className="panel"><h3>绑定频道</h3>{channelError ? <StatePanel code="API" title="频道绑定数据不可用" description={`${channelError}。当前 API 未返回数据，页面不会生成 Mock 绑定。`} error /> : channels.length ? <ul className="usage-list">{channels.map((channel) => <li key={channel.id}><div><strong>{channel.name}</strong><span>{channel.platform || "未指定平台"} · {channel.status}</span></div><code>{detail.versions.find((version) => version.id === channel.defaultComposition.skillVersionId)?.version ?? channel.defaultComposition.skillVersionId}</code></li>)}</ul> : <StatePanel code="00" title="尚未绑定频道" description="频道 API 已成功返回，但没有频道引用该 Skill 的任何版本。" />}</section><section className="panel"><h3>真实 Run</h3>{runError ? <StatePanel code="API" title="Run 数据不可用" description={`${runError}。当前 API 未返回真实 Run，页面不会生成示例记录。`} error /> : runs.length ? <div className="run-usage-table" role="region" aria-label="真实 Run 数据"><table><thead><tr><th>Run</th><th>版本</th><th>状态 / 失败原因</th><th>耗时</th><th>成本</th><th>创建时间</th></tr></thead><tbody>{runs.map((run) => { const failure = run.stepsAvailable === false ? undefined : run.steps.find((step) => step.error)?.error?.message; const duration = run.stepsAvailable === false ? "—" : `${Math.max(0, (Date.parse(run.updatedAt) - Date.parse(run.createdAt)) / 1000).toFixed(1)} 秒`; const cost = run.costAvailable === false ? "—" : `${run.estimate.cost.currency} ${run.estimate.cost.amount.toFixed(2)}`; return <tr key={run.id}><td><Link href={`/projects/${run.id}`}>{run.topic || run.id}</Link></td><td>{detail.versions.find((version) => version.id === run.composition.skillVersionId)?.version ?? "未知版本"}</td><td><Badge tone={run.status === "succeeded" ? "success" : run.status === "failed" ? "warning" : "neutral"}>{run.status}</Badge>{failure ? <span className="run-failure">{failure}</span> : run.stepsAvailable === false ? <span className="run-failure">步骤详情 —</span> : null}</td><td>{duration}</td><td>{cost}</td><td>{displayDate(run.createdAt)}</td></tr>; })}</tbody></table></div> : <StatePanel code="00" title="没有真实 Run" description="Run API 已成功返回，但没有 Run 引用该 Skill 的任何版本。" />}</section></div></section>;
}

function PublishChecks({ adapter, detail, onUpdate }: { adapter: Adapter; detail: SkillDetail; onUpdate: (value: SkillDetail) => void }) {
  const draft = draftVersion(detail); const [report, setReport] = useState<ValidationReport | null>(null); const [running, setRunning] = useState(false); const [status, setStatus] = useState(draft?.state === "ready" ? "服务端已记录该版本校验通过，可以直接发布或重新运行校验。" : draft ? "尚未运行本次草稿的服务端发布校验。" : "没有待发布草稿。已发布版本保持不可变。");
  async function validate() { if (!draft) return; setRunning(true); setStatus("正在运行服务端发布校验…"); setReport(null); const result = await adapter.validateVersion(detail.skill.id, draft.id); setRunning(false); if (!result.ok) { setStatus(`校验失败：${result.error.message}`); return; } const nextState = result.data.ready ? "ready" : "rejected"; onUpdate({ ...detail, skill: { ...detail.skill, status: result.data.ready ? "ready" : "draft", draftVersionId: draft.id }, versions: detail.versions.map((item) => item.id === draft.id ? { ...item, state: nextState, revision: result.data.revision } : item) }); setReport(result.data); setStatus(result.data.ready ? "全部服务端门禁通过，可以发布。" : `仍有 ${result.data.checks.filter((check) => !check.passed).length} 项未通过；版本仍可编辑，保存后可再次校验。`); }
  async function publish() { if (!draft || !(report?.ready || draft.state === "ready")) return; setRunning(true); setStatus("正在发布不可变版本…"); const result = await adapter.publishVersion(detail.skill.id, draft.id, draft.releaseNotes || "通过发布检查"); setRunning(false); if (!result.ok) { setStatus(`发布失败：${result.error.message}`); return; } onUpdate({ ...detail, skill: { ...detail.skill, status: "published", currentVersionId: result.data.id, draftVersionId: undefined }, versions: detail.versions.map((item) => item.id === result.data.id ? result.data : item) }); setReport(null); setStatus(`版本 ${result.data.version} 已发布并锁定；后续修改必须创建新草稿。`); }
  const localChecks = draft ? [{ label: "待发布版本存在", passed: true }, { label: "输入 Schema 已定义", passed: Object.keys(asRecord(draft.spec.inputSchema.properties)).length > 0 }, { label: "输出契约已声明", passed: draft.spec.outputContract.fields.length > 0 }, { label: "至少 1 个测试主题", passed: draft.testTopics.length >= 1 }] : [];
  return <section aria-labelledby="publish-title"><div className="section-heading"><div><p className="eyebrow">RELEASE GATES</p><h2 id="publish-title">发布检查</h2></div>{draft ? <Badge tone="warning">草稿 {draft.version}</Badge> : <Badge tone="success">无待发布内容</Badge>}</div><p className="status-line" role="status" aria-live="polite" aria-busy={running}>{status}</p>{!draft ? <StatePanel code="LOCK" title={detail.skill.permissions.edit ? "当前没有草稿" : "官方发布版本只读"} description={detail.skill.permissions.edit ? "发布版本不可覆盖。请先从当前版本创建一个后续草稿。" : "官方 Skill 不能由当前工作区发布；分叉后可独立测试和发布。"}>{detail.skill.permissions.edit ? <Link className="button" href={`/skills/${detail.skill.id}/versions`}>创建后续草稿</Link> : <Link className="button" href={`/skills/new?method=fork&source=${encodeURIComponent(detail.skill.id)}`}>分叉 Skill</Link>}</StatePanel> : <div className="publish-grid"><section className="panel"><h3>本地预检查</h3><ul className="check-list">{localChecks.map((check) => <li key={check.label} className={check.passed ? "" : "is-pending"}>{check.label}</li>)}</ul><p className="muted">本地预检查只用于提前定位明显缺口，不替代服务端校验。</p></section><section className="panel"><h3>服务端校验结果</h3>{report ? <><ul className="validation-list">{report.checks.map((check) => <li key={check.id} data-pass={check.passed}><div><strong>{check.label}</strong><span>{check.message}</span></div><Badge tone={check.passed ? "success" : check.severity === "error" ? "warning" : "neutral"}>{check.passed ? "通过" : check.severity}</Badge></li>)}</ul><p className="muted">预估校验成本：{report.estimatedCost.currency} {report.estimatedCost.amount.toFixed(2)}</p></> : draft.state === "ready" ? <StatePanel code="READY" title="服务端校验已通过" description="版本状态与 revision 已从控制 API 恢复；可以直接发布，或重新运行校验查看完整检查项。" /> : <StatePanel code="API" title="等待服务端校验" description="点击运行后才会展示真实校验结果；页面不会自行生成通过状态。" />}</section></div>}<div className="editor-savebar theme-inverse"><span />{draft ? <div className="button-row"><button className="button-secondary" type="button" onClick={() => void validate()} disabled={running}>{running ? "处理中…" : "运行发布校验"}</button>{detail.skill.permissions.publish ? <button className="button" type="button" onClick={() => void publish()} disabled={running || !(report?.ready || draft.state === "ready")}>发布不可变版本</button> : null}</div> : null}</div></section>;
}
